behaviours:
  - name: http-simple-response
    description: Empty response body
    port: 8081
  - name: http-simple-response
    description: Not Found error
    port: 8082
    status_code: 404
  - name: http-simple-response
    description: Server Error
    port: 8083
    status_code: 500
  - name: http-simple-response
    description: Wrong content type returned
    port: 8084
    content_type: "application/json; charset: utf-8"
    body: foo